# Generated by Django 5.2.4 on 2025-07-26 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='TipoVariacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('disponible', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('es_destacado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.marca')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/imagenes/')),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
            ],
            options={
                'verbose_name_plural': 'Imágenes de Producto',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ValorVariacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('tipo_variacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='productos.tipovariacion')),
            ],
            options={
                'unique_together': {('tipo_variacion', 'valor')},
            },
        ),
        migrations.CreateModel(
            name='VariacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('imagen_variacion', models.ImageField(blank=True, null=True, upload_to='productos/variaciones/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaciones', to='productos.producto')),
                ('valores', models.ManyToManyField(to='productos.valorvariacion')),
            ],
            options={
                'verbose_name_plural': 'Variaciones de Producto',
                'unique_together': {('producto', 'sku')},
            },
        ),
    ]
