# Generated by Django 5.2.4 on 2025-07-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacionproducto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
