# Generated by Django 5.2.4 on 2025-07-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_pedido_itempedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
